### ISSUE TITLE
Flask API

### ISSUE THREAD

**Issue by AyoubSelmi** [SubhamIO/Image-Captioning-using-Attention-Mechanism-Local-Attention-and-Global-Attention-#2]
I come from the medium article https://medium.com/swlh/image-captioning-using-attention-mechanism-f3d7fc96eb0e and I really enjoyed learning about image captionning through your really informative tutorial. I wanted to go further and deploy the image captioning model using flask and I got stuck to get the api working as  I didn't know what to put into image_captnng.py which is imported in  app.py (from image_captnng import *)
any help please ?

**Comment by SubhamIO** [comment]
Hi, Thanks for pointing it out. I have added the file image_captnng.py. Check it out

**Comment by AyoubSelmi** [comment]
everything works great. thanks for your help !

**Comment by ooza** [comment]
@AyoubSelmi 
Do you retrain the model from scratch? if yes, how was the result? can you share your best checkpoint in order to test it please?
Thanks
