### ISSUE TITLE
Beam search not predicting the sentence completely

### ISSUE THREAD

**Issue by caffeine-lab** [SubhamIO/Image-Captioning-using-Attention-Mechanism-Local-Attention-and-Global-Attention-#3]
Hi,

I am using Greedy search and Beam search to predict captions.

So for the greedy search, I am getting a result in a complete sentence.

e.g: a man is standing on a mountain

But when I predict with beam search I simply get 2-3 words mostly.

eg: a man standing
or man on a

something like this.

**Comment by SubhamIO** [comment]
@caffeine-lab , it might happen..  I am doing some modifications on beam search..  Will upload optimised one soon.. Till then use Greedy approach.

**Comment by caffeine-lab** [comment]
@SubhamIO , Thank you that would be nice. But currently what is the working solution you have? How did you make the Beam search work for the results you have demonstrated.

**Comment by Hrishi1999** [comment]
Any updates?

**Comment by caffeine-lab** [comment]
@SubhamIO I could notice that you closed the issue. Is the problem fixed?

**Comment by SubhamIO** [comment]
@caffeine-lab  I am not getting enough time to look into this. Been busy at office work.  If you have a solution you are free to propose. Or just wait for me to get free.
Thanks
